USE enviromonitor;

INSERT INTO metadata (category, quantity, symbol, unit,	unit_description, measurement_frequency, safe_level, reference, sensor, data_url) VALUES
    ('Air quality',	'Nitrogen dioxide',	'NO2',	'ug/m3',	'microgrammes per cubic metre',	'Hourly',	200,	'https://uk-air.defra.gov.uk/air-pollution/daqi?view=more-info&pollutant=no2#pollutant',	'Airly',	'https://airly.org/en/features/air-quality-sensors/'),
    ('Air quality',	'Sulphur dioxide',	'SO2',	'ug/m3',	'microgrammes per cubic metre',	'Hourly',	266,	'https://uk-air.defra.gov.uk/air-pollution/daqi?view=more-info&pollutant=so2#pollutant',	'Airly',	'https://airly.org/en/features/air-quality-sensors/'),
    ('Air quality',	'Particulate matter <= 2.5 microns in diameter',	'PM2.5',	'ug/m3',	'microgrammes per cubic metre',	'Hourly',	35,	'https://www.gov.uk/government/statistics/air-quality-statistics/concentrations-of-particulate-matter-pm10-and-pm25',	'Airly',	'https://airly.org/en/features/air-quality-sensors/'),
    ('Air quality',	'Particulate matter <= 10 microns in diameter',	'PM10',	'ug/m3',	'microgrammes per cubic metre',	'Hourly',	50,	'https://www.gov.uk/government/statistics/air-quality-statistics/concentrations-of-particulate-matter-pm10-and-pm25',	'Airly',	'https://airly.org/en/features/air-quality-sensors/'),
    ('Water quality',	'Nitrite',	'-NO3',	'mg/l',	'milligrammes per litre',	'Hourly',	3,	'https://cdn.who.int/media/docs/default-source/wash-documents/water-safety-and-quality/chemical-fact-sheets-2022/nitrate-and-nitrite-fact-sheet-2022.pdf?sfvrsn=a65406e9_2&download=true',	'ClearWater',	'https://clearwatersensors.com/nitrate-sensor.html'),
    ('Water quality',	'Nitrate',	'-NO2',	'mg/l',	'milligrammes per litre',	'Hourly',	50,	'https://cdn.who.int/media/docs/default-source/wash-documents/water-safety-and-quality/chemical-fact-sheets-2022/nitrate-and-nitrite-fact-sheet-2022.pdf?sfvrsn=a65406e9_2&download=true',	'ClearWater',	'https://clearwatersensors.com/nitrate-sensor.html'),
    ('Water quality',	'Phosphate',	'-PO4',	'mg/l',	'milligrammes per litre',	'Hourly',	0.1,	'https://assets.publishing.service.gov.uk/media/5a7b1f23ed915d3ed90624fc/defra-stats-observatory-indicators-da3-120224.pdf',	'ClearWater',	'https://clearwatersensors.com/phosphate-sensor.html'),
    ('Water quality',	'Escherichia coli ',	'EC',	'cfu/100ml',	'Colony forming units (cfu) per 100ml ',	'Daily',	500,	'https://environment.data.gov.uk/bwq/profiles/help-understanding-data.html',	'ALERT',	'https://www.digital-water.city/solution/sensors-for-real-time-in-situ-e-coli-and-enterococci-measurements/'),
    ('Water quality',	'Intestinal enterococci ',	'IE',	'cfu/100ml',	'Colony forming units (cfu) per 100ml ',	'Daily',	185,	'https://environment.data.gov.uk/bwq/profiles/help-understanding-data.html',	'ALERT',	'https://www.digital-water.city/solution/sensors-for-real-time-in-situ-e-coli-and-enterococci-measurements/'),
    ('Weather',	'Air temperature',	'T',	'C',	'Degrees Celcius',	'Hourly',	NULL,	NULL,	'Netvox R712',	'https://www.alliot.co.uk/product/netvox-outdoor-temperature-and-humidity-sensor/'),
    ('Weather',	'Humidity',	'H',	'%',	'Percentage',	'Hourly',	NULL,	NULL,	'Netvox R712',	'https://www.alliot.co.uk/product/netvox-outdoor-temperature-and-humidity-sensor/'),
    ('Weather',	'Wind speed',	'WS',	'm/s',	'Metres per second',	'Hourly',	NULL,	NULL,	'Vaisala WM80',	'https://www.vaisala.com/en/products/ultrasonic-wind-sensor-wm80'),
    ('Weather',	'Wind direction',	'WD',	'degree',	'Degrees from north',	'Hourly',	NULL,	NULL,	'Vaisala WM80',	'https://www.vaisala.com/en/products/ultrasonic-wind-sensor-wm80');